ALTER TABLE coins ADD COLUMN IF NOT EXISTS metadata_status VARCHAR(20) NOT NULL DEFAULT 'pending';
ALTER TABLE coins ADD COLUMN IF NOT EXISTS metadata_last_error TEXT;
ALTER TABLE coins ADD COLUMN IF NOT EXISTS metadata_updated_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS market_global (
  id SMALLINT PRIMARY KEY DEFAULT 1,
  total_market_cap NUMERIC NOT NULL DEFAULT 0,
  total_volume NUMERIC NOT NULL DEFAULT 0,
  btc_dominance NUMERIC NOT NULL DEFAULT 0,
  active_coins INTEGER NOT NULL DEFAULT 0,
  markets INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
